services:
  firebase-emulator:
    image: andreysenov/firebase-tools:latest
    container_name: firebase-emulator
    ports:
      # Firestore
      - '8080:8080'
      # Realtime Database
      - '9000:9000'
      # Storage
      - '9199:9199'
      # Auth
      - '9099:9099'
      # Pub/Sub
      - '8085:8085'
      # Hosting
      - '5002:5000'
      # Functions
      - '5001:5001'
      # Emulator UI
      - '4000:4000'
    volumes:
      - ./data:/home/node
      - ./firebase.json:/home/node/firebase.json
    environment:
      FIREBASE_EMULATOR_HUB: '0.0.0.0:4000'
    command: >
      firebase emulators:start
      --only ui,firestore,auth,storage,pubsub
      --import=/home/node/firebase
      --export-on-exit=/home/node/firebase
